### ISSUE TITLE
'No such file or directory - uname' when running on Ruby 2.2.0

### ISSUE THREAD

**Issue by Portalboy** [mogest/nitra#10]
Received the following error when executing `bundle exec nitra --rspec` on Ruby 2.2.0:
`
C:/Ruby22/lib/ruby/gems/2.2.0/gems/nitra-0.9.6/lib/nitra/utils.rb:8:in``': No such file or directory - uname (Errorno::ENOENT)
`
![nitra](https://cloud.githubusercontent.com/assets/6773480/18452566/00c2cf6a-7901-11e6-9ee6-dd5506babf4d.png)

Am I doing something wrong?

**Comment by mogest** [comment]
Hi @Portalboy.  Sorry to say but nitra was only designed to work on Unix-like systems.

**Comment by Portalboy** [comment]
http://www.nooooooooooooooo.com/
